commit

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,16 +1,10 @@
 #!/bin/bash
 
-# Check if $PYFILE is set
-if [ -z "$PYFILE" ]; then
-    echo "Error: Environment variable PYFILE is not set."
-    exit 1
-fi
+[ -z "$PYFILE" ] && { echo "Error: PYFILE environment variable not set."; exit 1; }
 
-# Extracting the directory path and filename
-DIR=$(dirname "$PYFILE")
-FILE=$(basename "$PYFILE")
-
-# Changing directory to the script directory and compiling
-echo "Compiling $FILE ..."
-cd "$DIR" || exit 1
-python3 -m py_compile "$FILE"
+output="${PYFILE%.py}.pyc"
+echo "Compiling $PYFILE ..." && \
+python3 -m py_compile "$PYFILE" && \
+mv -f "__pycache__/$PYFILE.cpython-*.pyc" "$output" && \
+rm -rf "__pycache__" && \
+echo "Compiled output: $output"
